from .explorer import EXPLORER_SYSTEM_PROMPT, EXPLORER_TOOLS
from .researcher import RESEARCHER_SYSTEM_PROMPT, RESEARCHER_TOOLS
from .implementer import IMPLEMENTER_SYSTEM_PROMPT, IMPLEMENTER_TOOLS
from .tester import TESTER_SYSTEM_PROMPT, TESTER_TOOLS
from .reviewer import REVIEWER_SYSTEM_PROMPT, REVIEWER_TOOLS

# role -> (system_prompt, allowed_tool_names)
SUBAGENT_REGISTRY = {
    "Explorer": (EXPLORER_SYSTEM_PROMPT, EXPLORER_TOOLS),
    "Researcher": (RESEARCHER_SYSTEM_PROMPT, RESEARCHER_TOOLS),
    "Implementer": (IMPLEMENTER_SYSTEM_PROMPT, IMPLEMENTER_TOOLS),
    "Tester": (TESTER_SYSTEM_PROMPT, TESTER_TOOLS),
    "Reviewer": (REVIEWER_SYSTEM_PROMPT, REVIEWER_TOOLS),
}
